spring:
  application:
    name: autorizadorPlaca
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

logging:
  level:
    com.autorizadorPlaca: DEBUG